require("alias")
require("events/EventCenter")
require("events/EventDefine")
require("common/Managers")
require("common/DevicePlatform")
GameManager = require("Manager/Base/GameManager"):getInstance()
UIUtil = require("common/UIUtil")
U3DUtil = require("common/U3DUtil")
LoopScrollViewUtil = require("common/LoopScrollViewUtil")
CircleLoopScrollViewUtil = require("common/CircleLoopScrollViewUtil")
LuaBehaviourUtil = require("common/LuaBehaviourUtil")
