local module = _ENV.module
local _G = _ENV._G
local sdp = require("sdp")
require("ProtoGameNet")
require("ProtoGameRole")
require("ProtoGameItem")
require("ProtoGameStrategy")
require("ProtoGameHero")
require("ProtoGameQuest")
require("ProtoGameStage")
require("ProtoGameGacha")
require("ProtoGameRoom")
require("ProtoGameShop")
require("ProtoGameAttract")
require("ProtoGameBaseStore")
require("ProtoGameMail")
require("ProtoGameRank")
require("ProtoGameStore")
require("ProtoGameSnsShare")
require("ProtoGameChat")
require("ProtoGameCastle")
require("ProtoGameReplaceArena")
require("ProtoGameSoloRaid")
require("ProtoGameHunting")
require("ProtoGameClientData")
require("ProtoGameGuide")
require("ProtoGameAfk")
require("ProtoGameRogue")
require("ProtoGameMerge")
require("ProtoGameLegacy")
require("ProtoGameBattle")
require("ProtoGameMisc")
require("ProtoGameLegacyStage")
require("ProtoGameRecommend")
require("ProtoGameActivity")
